//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lvnKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lvnKhoa()
        {
            this.lvnSinhVien = new HashSet<lvnSinhVien>();
        }
    
        public string LvnMaKH { get; set; }
        public string LvnTenKH { get; set; }
        public Nullable<bool> Lvn_Trang_Thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lvnSinhVien> lvnSinhVien { get; set; }
    }
}
