//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lvnSinhVien
    {
        public string LvnMaSV { get; set; }
        public string LvnHoSV { get; set; }
        public string LvnTenSV { get; set; }
        public Nullable<System.DateTime> LvnNgaySinh { get; set; }
        public Nullable<bool> LvnPhai { get; set; }
        public string LvnPhone { get; set; }
        public string LvnEmail { get; set; }
        public string LvnMaKH { get; set; }
    
        public virtual lvnKhoa lvnKhoa { get; set; }
    }
}
